version: "3"

services:

  golang:
    tty: true
    # restart: always
    container_name: img_downloader_golang
    build:
      context: ./golang
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    # настройки БД
    # ports:
    #   - "8000:8000"
    environment:
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: 84235220884
      MYSQL_DATABASE: downloader
      MYSQL_IP: 172.2.1.2
      MYSQL_PORT: 3306      
    networks:
      img_downloader:
        ipv4_address: 172.2.1.6
 
  mysql:
    tty: false
    # restart: always
    container_name: img_downloader_mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    # настройки БД
    environment:
      MYSQL_ROOT_PASSWORD: 84235220884
      MYSQL_DATABASE: downloader
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    networks:
      img_downloader:
        ipv4_address: 172.2.1.2  

  phpmyadmin:
    tty: false
    # restart: always
    container_name: img_downloader_phpmyadmin
    image: phpmyadmin:latest
    # ports:
    #   - "3306:3306"
    # настройки БД
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 84235220884
      PMA_HOST: 172.2.1.2
      PMA_PORT: 3306
    networks:
      img_downloader:
        ipv4_address: 172.2.1.3

  postgres:
    container_name: img_downloader_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      img_downloader:
        ipv4_address: 172.2.1.4

  pgadmin:
    tty: false
    # restart: always
    container_name: img_downloader_pgadmin
    image: dpage/pgadmin4:latest
    # ports:
    #   - "3306:3306"
    # настройки БД
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin4:/var/lib/pgadmin
    networks:
      img_downloader:
        ipv4_address: 172.2.1.5
  
  

# создание сети
networks:
  # название сети
  img_downloader:
    driver: bridge #драйвер
    ipam:
      driver: default
      config:
        - subnet: 172.2.1.0/24
